# -*- coding: utf-8 -*-
"""Mini Project_Keysha Adya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bMw9lYAkrb7nyeKn2eSossF8ZNYJtzwv
"""

import csv
import io
import matplotlib.pyplot as plt
from google.colab import files

print("=== SILAKAN UPLOAD FILE '.fasta' ===")
uploaded = files.upload()

nama_file_uploaded = list(uploaded.keys())[0]
print(f"\n[INFO] Berhasil membaca file: {nama_file_uploaded}\n")

# ==========================================================
# 2. MEMBACA FILE FASTA & DISIMPAN DALAM LIST
# ==========================================================
def baca_fasta_colab(konten_file):
    sekuens_list = []
    current_id = ""
    current_seq = ""

    for line in konten_file.decode('utf-8').splitlines():
        line = line.strip()
        if line.startswith(">"):
            if current_id:
                sekuens_list.append({"id": current_id, "sekuens": current_seq})
            current_id = line[1:]
            current_seq = ""
        else:
            current_seq += line

    if current_id:
        sekuens_list.append({"id": current_id, "sekuens": current_seq})

    return sekuens_list

# ===================================================================
# 3. MENGHITUNG FREKUENSI NUKLEOTIDA & GC CONTENT (DICTIONARY)
# ===================================================================
def analisis_pipeline(sekuens_list):
    hasil_analisis = []

    for item in sekuens_list:
        seq = item["sekuens"].upper()

        frekuensi = {'A': 0, 'T': 0, 'G': 0, 'C': 0}
        for nukleotida in seq:
            if nukleotida in frekuensi:
                frekuensi[nukleotida] += 1

        total_basa = len(seq)
        gc_count = frekuensi['G'] + frekuensi['C']
        gc_content = (gc_count / total_basa) * 100 if total_basa > 0 else 0

        hasil_analisis.append({
            "id": item["id"],
            "A": frekuensi['A'],
            "T": frekuensi['T'],
            "G": frekuensi['G'],
            "C": frekuensi['C'],
            "GC_Content": round(gc_content, 2)
        })

    return hasil_analisis

# ===================================================================
# 4. EKSEKUSI UTAMA PIPELINE
# ===================================================================
data_mentah = baca_fasta_colab(uploaded[nama_file_uploaded])
hasil_proses = analisis_pipeline(data_mentah)

# Mengurutkan data berdasarkan GC Content
hasil_terurut = sorted(hasil_proses, key=lambda x: x['GC_Content'], reverse=True)

print("=== 3 SEKUENS TERBAIK BERDASARKAN GC CONTENT ===")
tiga_terbaik = hasil_terurut[:3]
for i, data in enumerate(tiga_terbaik, 1):
    print(f"{i}. ID: {data['id'][:60]}... | GC Content: {data['GC_Content']}%")

with open("hasil_analisis.csv", "w", newline="") as csv_file:
    fieldnames = ["id", "A", "T", "G", "C", "GC_Content"]
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(hasil_proses)
print("\n[INFO] Sukses membuat file 'hasil_analisis.csv'!\n")

# ===================================================================
# 5. VISUALISASI GRAFIK
# ===================================================================
gc_values = [data['GC_Content'] for data in hasil_proses]

# Mengganti sumbu X jadi angka 1, 2, 3 agar teks panjangnya tidak tabrakan hitam
sumbu_x_angka = [str(i+1) for i in range(len(gc_values))]

plt.figure(figsize=(10, 5.5))

# Memasukkan kode warna: Pink pastel, Ungu pastel, Kuning pastel cerah
warna_pilihan = ['#FF69B4', '#9370DB', '#FFD700', '#ADD8E6']
colors_pola = (warna_pilihan * (len(gc_values) // 3 + 1))[:len(gc_values)]

# Gambar grafik batangnya
bars = plt.bar(sumbu_x_angka, gc_values, color=colors_pola, edgecolor='#4A4A4A', width=0.55, zorder=3)

# Label teks grafik
plt.ylabel('GC Content (%)', fontsize=12, fontweight='bold', labelpad=10)
plt.xlabel('Sekuens ID (Nomor Urut)', fontsize=12, fontweight='bold', labelpad=10)
plt.title('Visualisasi Analisis GC Content - Pipeline Gen PETase', fontsize=14, fontweight='bold', pad=15)

plt.ylim(0, 100) # Batas atas sumbu Y diubah ke 100% biar pas
plt.grid(axis='y', linestyle='--', alpha=0.5, zorder=0)

# Memunculkan label angka persen di atas masing-masing batang
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 2,
             f'{height}%',
             ha='center', va='bottom', fontsize=10, fontweight='bold', color='#333333')

plt.tight_layout()
plt.savefig('grafik_gc_content.png', dpi=300)
plt.show() # Tampilkan grafiknya